# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuisines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('promotion', models.TextField(blank=True, max_length=400, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisines.Cuisine')),
            ],
        ),
    ]
