# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cuisines.Cuisine'),
        ),
    ]
