# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:59
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20170711_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
