# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
