# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170711_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='items.Allergen'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
